### ISSUE TITLE
Started a game with two people and got an error

### ISSUE THREAD

**Issue by nwalke** [CharlieHess/slack-poker-bot#12] opened 2015-09-01 19:14 UTC
This happened as soon as it said "let's start the game"

```
/Users/nwalke/projects/slack-poker-bot/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Cannot read property 'send' of undefined
    at TexasHoldem.dealPlayerCards (/Users/nwalke/projects/slack-poker-bot/src/texas-holdem.js:503:11)
    at TexasHoldem.playHand (/Users/nwalke/projects/slack-poker-bot/src/texas-holdem.js:116:10)
    at /Users/nwalke/projects/slack-poker-bot/src/texas-holdem.js:70:27
    at /Users/nwalke/projects/slack-poker-bot/node_modules/rx/dist/rx.js:4924:20
    at tryCatcher (/Users/nwalke/projects/slack-poker-bot/node_modules/rx/dist/rx.js:567:29)
    at InnerObserver.onNext (/Users/nwalke/projects/slack-poker-bot/node_modules/rx/dist/rx.js:4806:43)
    at InnerObserver.tryCatcher (/Users/nwalke/projects/slack-poker-bot/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/nwalke/projects/slack-poker-bot/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/nwalke/projects/slack-poker-bot/node_modules/rx/dist/rx.js:1710:35)
    at scheduleItem (/Users/nwalke/projects/slack-poker-bot/node_modules/rx/dist/rx.js:2961:16)
```

**Comment by fastest963** [comment] 2015-09-01 20:58
This also happened to me. Playing with more people seemed to fix it.

**Comment by CharlieHess** [comment] 2015-09-01 22:05
Duplicate of #22.

**Closed by CharlieHess** 2015-09-01 22:05 UTC
