### ISSUE TITLE
All-in -> Fold results in the winner of the hand losing his entire stack

### ISSUE THREAD

**Issue by rkrn** [CharlieHess/slack-poker-bot#30] opened 2015-09-03 00:54 UTC
To replicate:

Start 2 player game. Either player raises to all-in. Then other player folds. The all-in player loses his entire stack and the player who folds wins the game.

![screen shot 2015-09-02 at 8 53 43 pm](https://cloud.githubusercontent.com/assets/8846770/9648263/98148b58-51b4-11e5-9039-74f6e96aa677.png)

**Comment by CharlieHess** [comment] 2015-09-03 01:52
Dupe of #23, I'll fix this stat.

**Closed by CharlieHess** 2015-09-03 01:52 UTC
